name: Update characters
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run scraper task
        run: bundle exec rake scrabby:characters
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update characters
          title: Update characters
          body: |
            Updates the `characters` data by scraping from the Harry Potter Wiki.
            This is an automatic generated pull request.
          branch: scrabby/update-characters
          branch-suffix: timestamp
          base: main
          add-paths: data/characters.csv
          delete-branch: true
          labels: characters, scrabby-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
