name: update-spells
on:
  schedule:
    - cron: '0 6 * * 5' # run every friday at 6am UTC
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run scrape spells task
        run: bundle exec rake scrabby:spells
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update spells
          title: Update spells
          body: |
            This is an automated pull request to update the `spells` data.
          branch: scrabby/update-spells
          branch-suffix: timestamp
          base: main
          add-paths: data/spells.csv
          delete-branch: true
          labels: spells, scrabby-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
